rm -rf /system/app/Stk
rm -rf /system/app/messaging
rm -rf /system/bin/rild
rm -rf /system/priv-app/CarrierConfig
rm -rf /system/priv-app/Dialer
rm -rf /system/priv-app/CallLogBackup
rm -rf /system/priv-app/CellBroadcastReceiver
rm -rf /system/priv-app/EmergencyInfo
rm -rf /system/priv-app/TeleService
